# -*- coding: utf-8 -*-
"""config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWKh4c5ic4oa3h3YswnDk5_lT1xalBxq
"""

"""
Configuration Module
Manages system configuration and parameters
"""

import json
import os

class Config:
    def __init__(self, config_file=None):
        """
        Initialize configuration

        Args:
            config_file: Path to JSON configuration file (optional)
        """
        # Default configuration
        self.config = {
            # Detection settings
            'detection_method': 'background_subtraction',  # 'yolo' or 'background_subtraction'
            'min_contour_area': 500,
            'max_disappeared': 30,

            # YOLO settings (if using YOLO)
            'yolo_weights': 'yolov3.weights',
            'yolo_config': 'yolov3.cfg',
            'yolo_names': 'coco.names',

            # Traffic monitoring settings
            'stop_line_y': None,  # Auto-calculated if None
            'lane_boundaries': None,  # List of x-coordinates [x1, x2, x3, ...]
            'light_cycle_frames': 300,  # Frames per light cycle (for simulation)

            # Speed estimation settings
            'pixel_to_meter': 0.05,  # Calibration factor (pixels to meters)
            'fps': 30,  # Video frame rate
            'speed_limit_kmh': 60,  # Speed limit in km/h

            # License plate OCR settings
            'tesseract_cmd': None,  # Path to tesseract executable (if not in PATH)
            'min_plate_width': 80,
            'min_plate_height': 20,
            'max_plate_width': 400,
            'max_plate_height': 150,
            'min_aspect_ratio': 2.0,
            'max_aspect_ratio': 6.0,

            # Output settings
            'output_dir': 'violations',
            'auto_record': False,  # Auto-record video output

            # Display settings
            'display_width': 1280,
            'display_height': 720,
        }

        # Load from file if provided
        if config_file and os.path.exists(config_file):
            self.load_from_file(config_file)

    def load_from_file(self, config_file):
        """Load configuration from JSON file"""
        try:
            with open(config_file, 'r') as f:
                user_config = json.load(f)
                self.config.update(user_config)
            print(f"Configuration loaded from {config_file}")
        except Exception as e:
            print(f"Error loading configuration: {e}")
            print("Using default configuration")

    def save_to_file(self, config_file):
        """Save current configuration to JSON file"""
        try:
            with open(config_file, 'w') as f:
                json.dump(self.config, f, indent=4)
            print(f"Configuration saved to {config_file}")
        except Exception as e:
            print(f"Error saving configuration: {e}")

    def get(self, key, default=None):
        """Get configuration value"""
        return self.config.get(key, default)

    def set(self, key, value):
        """Set configuration value"""
        self.config[key] = value

    def update(self, updates):
        """Update multiple configuration values"""
        self.config.update(updates)

    def print_config(self):
        """Print current configuration"""
        print("\n" + "="*50)
        print("CURRENT CONFIGURATION")
        print("="*50)
        for key, value in sorted(self.config.items()):
            print(f"{key:30s}: {value}")
        print("="*50 + "\n")


def create_default_config_file(filename='config.json'):
    """Create a default configuration file"""
    config = Config()
    config.save_to_file(filename)
    print(f"Default configuration file created: {filename}")
    print("Edit this file to customize your settings")


if __name__ == "__main__":
    # Create default config file when run directly
    create_default_config_file()