# -*- coding: utf-8 -*-
"""test_system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121P-flF3xKuMjRNn9ESHiASDh9DtVeDn
"""

"""
System Test Script
Tests individual components of the traffic violation detection system
"""

import cv2
import numpy as np
from config import Config
from vehicle_detector import VehicleDetector
from violation_monitor import ViolationMonitor
from license_plate_ocr import LicensePlateOCR

def test_vehicle_detection():
    """Test vehicle detection module"""
    print("\n" + "="*50)
    print("Testing Vehicle Detection")
    print("="*50)

    config = Config()
    detector = VehicleDetector(config)

    # Create a test frame
    test_frame = np.zeros((480, 640, 3), dtype=np.uint8)

    # Draw some rectangles to simulate vehicles
    cv2.rectangle(test_frame, (100, 200), (200, 300), (255, 255, 255), -1)
    cv2.rectangle(test_frame, (300, 250), (400, 350), (255, 255, 255), -1)

    # Detect vehicles
    detections = detector.detect(test_frame)

    print(f"Detected {len(detections)} vehicles")
    for i, det in enumerate(detections):
        x, y, w, h, conf, track_id = det
        print(f"  Vehicle {i+1}: bbox=({x},{y},{w},{h}), conf={conf:.2f}, id={track_id}")

    print("✓ Vehicle detection test completed")
    return True

def test_violation_monitor():
    """Test violation monitoring module"""
    print("\n" + "="*50)
    print("Testing Violation Monitor")
    print("="*50)

    config = Config()
    config.set('stop_line_y', 300)
    config.set('lane_boundaries', [200, 400, 600])
    monitor = ViolationMonitor(config)

    # Create test frame
    test_frame = np.zeros((480, 640, 3), dtype=np.uint8)

    # Simulate detections
    detections = [
        (100, 250, 80, 60, 0.9, 1),  # Vehicle before stop line
        (300, 310, 80, 60, 0.9, 2),  # Vehicle after stop line
        (150, 200, 80, 60, 0.9, 3),  # Vehicle in lane
    ]

    # Set traffic light to RED
    monitor.traffic_light_state = 'RED'

    # Check violations
    violations, annotated_frame = monitor.check_violations(test_frame, detections, 1)

    print(f"Detected {len(violations)} violations")
    for violation in violations:
        print(f"  Type: {violation['type']}, Vehicle ID: {violation['track_id']}")

    print("✓ Violation monitor test completed")
    return True

def test_license_plate_ocr():
    """Test license plate OCR module"""
    print("\n" + "="*50)
    print("Testing License Plate OCR")
    print("="*50)

    config = Config()
    ocr = LicensePlateOCR(config)

    if not ocr.tesseract_available:
        print("⚠ Tesseract not available, skipping OCR test")
        return False

    # Create synthetic license plate image
    plate_img = np.ones((100, 400, 3), dtype=np.uint8) * 255
    cv2.putText(plate_img, "ABC 1234", (50, 60),
                cv2.FONT_HERSHEY_SIMPLEX, 1.5, (0, 0, 0), 3)

    # Detect plates
    test_frame = np.zeros((480, 640, 3), dtype=np.uint8)
    test_frame[200:300, 120:520] = plate_img

    results, annotated = ocr.process_frame(test_frame)

    print(f"Detected {len(results)} license plates")
    for result in results:
        print(f"  Text: {result['text']}, BBox: {result['bbox']}")

    print("✓ License plate OCR test completed")
    return True

def test_config():
    """Test configuration module"""
    print("\n" + "="*50)
    print("Testing Configuration")
    print("="*50)

    config = Config()

    # Test get
    method = config.get('detection_method')
    print(f"Detection method: {method}")

    # Test set
    config.set('test_param', 'test_value')
    value = config.get('test_param')
    print(f"Test parameter: {value}")

    # Test save/load
    config.save_to_file('test_config.json')
    config2 = Config('test_config.json')
    value2 = config2.get('test_param')

    import os
    os.remove('test_config.json')

    assert value == value2, "Config save/load failed"

    print("✓ Configuration test completed")
    return True

def create_sample_video():
    """Create a sample video for testing"""
    print("\n" + "="*50)
    print("Creating Sample Test Video")
    print("="*50)

    width, height = 640, 480
    fps = 30
    duration = 10  # seconds

    fourcc = cv2.VideoWriter_fourcc(*'XVID')
    out = cv2.VideoWriter('sample_traffic.avi', fourcc, fps, (width, height))

    for frame_num in range(fps * duration):
        # Create frame
        frame = np.zeros((height, width, 3), dtype=np.uint8)

        # Draw road
        cv2.rectangle(frame, (0, height//2), (width, height), (50, 50, 50), -1)

        # Draw lanes
        for x in [width//3, 2*width//3]:
            for y in range(height//2, height, 20):
                cv2.line(frame, (x, y), (x, y+10), (255, 255, 255), 2)

        # Draw stop line
        stop_y = int(height * 0.7)
        cv2.line(frame, (0, stop_y), (width, stop_y), (0, 0, 255), 3)

        # Animated vehicle
        vehicle_x = int((frame_num / (fps * duration)) * width)
        vehicle_y = int(height * 0.6)
        cv2.rectangle(frame, (vehicle_x, vehicle_y),
                     (vehicle_x + 80, vehicle_y + 60), (0, 255, 255), -1)
        cv2.rectangle(frame, (vehicle_x, vehicle_y),
                     (vehicle_x + 80, vehicle_y + 60), (255, 255, 255), 2)

        # Draw traffic light
        light_color = (0, 0, 255) if (frame_num // 60) % 2 == 0 else (0, 255, 0)
        cv2.circle(frame, (width - 50, 50), 20, light_color, -1)

        out.write(frame)

    out.release()
    print("✓ Sample video created: sample_traffic.avi")
    print("  Run: python main.py --video sample_traffic.avi")
    return True

def run_all_tests():
    """Run all tests"""
    print("\n" + "="*60)
    print("TRAFFIC VIOLATION DETECTION SYSTEM - TEST SUITE")
    print("="*60)

    tests = [
        ("Configuration", test_config),
        ("Vehicle Detection", test_vehicle_detection),
        ("Violation Monitor", test_violation_monitor),
        ("License Plate OCR", test_license_plate_ocr),
        ("Sample Video", create_sample_video),
    ]

    results = []
    for name, test_func in tests:
        try:
            result = test_func()
            results.append((name, result))
        except Exception as e:
            print(f"✗ {name} test failed: {e}")
            results.append((name, False))

    # Print summary
    print("\n" + "="*60)
    print("TEST SUMMARY")
    print("="*60)
    for name, result in results:
        status = "✓ PASSED" if result else "✗ FAILED"
        print(f"{name:30s}: {status}")

    passed = sum(1 for _, r in results if r)
    total = len(results)
    print(f"\nTotal: {passed}/{total} tests passed")
    print("="*60 + "\n")

if __name__ == "__main__":
    run_all_tests()